// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ast_operationsJs = require("./ast_operations.js");

function transform(prim, prim$1, prim$2) {
  return Ast_operationsJs(prim, prim$1, prim$2);
}

function convert(name, source, useTailwind) {
  return Ast_operationsJs(name, source, useTailwind);
}

exports.transform = transform;
exports.convert = convert;
/* ./ast_operations.js Not a pure module */
