// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Ast_operationsJs = require("./ast_operations.js");
var HtmlConverter$LoginForm = require("./HtmlConverter.bs.js");

var htmlTestCases = [];

var svgTestCases = [];

var testCaseFiles = Belt_Array.concat(htmlTestCases, svgTestCases);

var testCases = Belt_Array.map(testCaseFiles, (function (filename) {
        return [
                filename,
                Fs.readFileSync("./testCases/" + filename, "utf8")
              ];
      }));

function test(param) {
  var testShellContent = {
    contents: "set -e;\necho 'RUNNING REFMT TESTS';\necho;\necho;"
  };
  Belt_Array.forEach(testCases, (function (testCase) {
          var data = testCase[1];
          var name = testCase[0];
          var filename = "/tmp/" + name + ".re";
          console.log("Appending test case: ", filename);
          testShellContent.contents = testShellContent.contents + ("\n" + ("head " + filename + "; /Users/s/.esy/3_______________________________________________________________________/i/opam__s__reason-7d161d4c/bin/refmt --in-place " + filename + ";\n             "));
          var result = function (param) {
            return HtmlConverter$LoginForm.convert(name, data, param);
          };
          Fs.writeFileSync(filename, "/* Original:\n\n*/\n\nlet result = (<> " + result + " </>)\n\n");
          
        }));
  Fs.writeFileSync("./test.sh", testShellContent.contents);
  
}

test(undefined);

exports.htmlTestCases = htmlTestCases;
exports.svgTestCases = svgTestCases;
exports.testCaseFiles = testCaseFiles;
exports.testCases = testCases;
exports.test = test;
/*  Not a pure module */
